/**
 * Centralized constants for sheet names, column indices, formats and enums.
 */

// Sheet/tab names
var SHEET_NAMES = {
  CONFIG: 'CONFIG',
  CONTAS_FIXAS: 'CONTAS_FIXAS',
  CONTAS_MENSAL: 'CONTAS_MENSAL',
  LOGS: 'LOGS'
};

// Column indices (1-based)
var CONFIG_COLUMNS = {
  PARAM: 1,
  VALUE: 2
};

var CONTAS_FIXAS_COLUMNS = {
  ID_CONTA: 1,
  NOME_CONTA: 2,
  CATEGORIA: 3,
  TIPO_PESSOA: 4,
  VALOR_PREVISTO: 5,
  DIA_RECORRENCIA: 6,
  METODO_PAGAMENTO: 7,
  OBSERVACOES: 8,
  ATIVA: 9
};

var CONTAS_MENSAL_COLUMNS = {
  ID_MENSAL: 1,
  ID_CONTA_ORIGEM: 2,
  NOME_CONTA: 3,
  CATEGORIA: 4,
  TIPO_PESSOA: 5,
  VALOR_PREVISTO: 6,
  VALOR_REAL: 7,
  VENCIMENTO: 8,
  DATA_PAGAMENTO: 9,
  PAGO: 10,
  ATRASADO: 11,
  METODO_PAGAMENTO: 12,
  ORIGEM: 13,
  NOTIFICACAO_ENVIADA: 14,
  OBSERVACOES: 15
};

// Formats
var DATE_FORMAT = 'dd/MM/yyyy';
var DATE_TIME_FORMAT = 'dd/MM/yyyy HH:mm';

// Status and origin enums
var STATUS = {
  PAGO: 'PAGO',
  EM_ABERTO: 'EM_ABERTO',
  ATRASADO: 'ATRASADO'
};

var ORIGEM = {
  FIXA: 'ORIGEM_FIXA',
  VARIAVEL: 'ORIGEM_VARIAVEL'
};

// Notification modes
var NOTIFICATION_MODES = {
  DIAS_ANTES: 'DIAS_ANTES',
  NO_DIA: 'NO_DIA',
  APOS_VENCIMENTO: 'APOS_VENCIMENTO'
};

// CONFIG keys used when mapping the sheet to an object
var CONFIG_KEYS = {
  EMAILS_NOTIFICACAO: 'EMAILS_NOTIFICACAO',
  DIAS_ANTES_VENCIMENTO: 'DIAS_ANTES_VENCIMENTO',
  ENVIAR_NO_DIA_DO_VENCIMENTO: 'ENVIAR_NO_DIA_DO_VENCIMENTO',
  ENVIAR_AVISO_APOS_VENCIMENTO: 'ENVIAR_AVISO_APOS_VENCIMENTO',
  HORA_ENVIO_DIARIO: 'HORA_ENVIO_DIARIO',
  FUSO_HORARIO: 'FUSO_HORARIO',
  MODO_CONTROLE_PF_PJ: 'MODO_CONTROLE_PF_PJ'
};
